insert into public.invitados (nombre_apellido, cupos) values
('Almenia', 2),
('William & Arlenis', 3),
('Ricardo', 1),
('Familia Bedoya', 4),
('Esteban Taborda', 1),
('Andres Abadia', 1),
('Nicolas & Lizeth', 3),
('Natalia', 1),
('Ana Ramires & Alfredo', 2),
('Luz Stella', 1),
('Rocio Casto', 1),
('Lola Esterh Murillo', 3),
('Raúl & Nancy Salomé', 3),
('Liz & Nelson & Danna & Majo & Santi', 5),
('Lady Luz & Carlos A & Duvan & Ana Isabella', 4),
('Luisa Erick & Juan Sebastian & Jesús David ', 4),
('Carlos Andrés & Daviana', 2),
('Eliza', 1),
('Erika & Mady & Shanty & Fredy', 4),
('Jeronimo', 1),
('Sophia', 1),
('Ediner & Maria de los angeles', 2),
('Jaime Posada & Catalina & Rebeca', 3),
('Marisol & Diego & Juan Diego', 3),
('Johana A & Mauricio', 2),
('Daniel & Sulay', 2),
('Quimbayo & Nohemi', 2),
('Luisa & Esneider', 2),
('Cristian', 2),
('Jenine Fryling & Jorge Marin', 2);