-- =========================================================
-- 02_invitados.sql
-- Carga inicial de invitados
-- =========================================================

insert into public.invitados (nombre_apellido, cupos_reservados, rol)
values
('Almenia', 2, null),
('William', 2, null),
('Arlenis', 2, null),
('Natalia', 2, null),
('Ricardo', 2, null),
('Jose', 2, null),
('Yarlis', 2, null),
('Rosa', 2, null),
('Ñato', 2, null),
('Marian', 2, null),
('Esteban', 2, 'Caballero de Honor'),
('Andres', 2, 'Caballero de Honor'),
('Nicolas', 2, 'Caballero de Honor'),
('Lizeth', 2, 'Acompañante de Nicolas'),
('Natalia', 2, null),
('Ana', 2, null),
('Esposo Ana', 2, null),
('Luz Stella', 2, null),
('Rocio', 2, null),
('Lola Sther', 2, null),
('Daniel', 2, 'Acompañante de Lola'),
('Niña', 2, 'Acompañante de Lola'),
('Raúl', 2, null),
('Nancy', 2, null),
('Liz', 2, null),
('Nelson', 2, null),
('Danna', 2, null),
('Majo', 2, null),
('Santi', 2, null),
('Lady Luz', 2, null),
('Carlos Alberto', 2, null),
('Duván', 2, null),
('Ana Isabella', 2, null),
('Luisa', 2, null),
('Erick', 2, null),
('Juan Sebastian', 2, null),
('Jesús David', 2, null),
('Carlos Andrés', 2, null),
('Daviana', 2, null),
('Salomé', 2, null),
('Eliza', 2, 'Dama de Honor'),
('Mady', 2, 'Dama de Honor'),
('Shanty', 2, 'Dama de Honor'),
('Erika', 2, null),
('Fredy', 2, null),
('Jeronimo', 2, null),
('Sophia', 2, null),
('Ediner', 2, null),
('Maria de los angeles', 2, null),
('Jaime Posada', 2, null),
('Catalina', 2, null),
('Rebeca', 2, null),
('Marisol', 2, null),
('Diego', 2, null),
('Juan Diego', 2, null),
('Johana A', 2, null),
('Mauricio', 2, null),
('Daniel', 2, null),
('Sulay', 2, null),
('Quimbayo', 2, null),
('Nohemi', 2, null),
('Luisa', 2, 'Cantante'),
('Esneider', 2, null),
('Cristian', 2, null),
('Jenine Fryling', 2, null),
('Jorge Marin', 2, null);
